name: Lint
on: [pull_request, push]
jobs:
  build:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
      - name: Lint backend
        working-directory: ./backend
        run: |
          npm ci
          npm run lint
